# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3536fb340ea4d3c1da2015b5fd47d318"
name = "volume discount "
handle = "volume-discount-86"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "dark-development-store.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
